# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{siskel}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JP Hastings-Spital", "Jon Dahl"]
  s.date = %q{2010-07-21}
  s.description = %q{Inspect a video/audio file for properties and metadata, using mediainfo}
  s.email = %q{jphastings@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "lib/siskel.rb",
     "test/fixtures/test_mediainfo_results.rb",
     "test/fixtures/tiny.mp4",
     "test/siskel_test.rb"
  ]
  s.homepage = %q{http://github.com/jphastings/AirVideo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A nippy video metadata inspector library}
  s.test_files = [
    "test/fixtures/test_mediainfo_results.rb",
     "test/siskel_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

